// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Current remote-control environment id exposed to remote-control clients.
 */
export type RemoteControlEnvironmentUpdatedNotification = { environmentId: string | null, };
